version: '3.7'

services:
  backend:
    build: ./simple-api
    container_name: my-api
    networks:
      - my-network
    depends_on:
      - database

  database:
    build: ./database
    container_name: my-db
    networks:
      - my-network
    volumes:
      - db-volume:/var/lib/postgresql/data

  frontend:
    build: ../devops-front
    container_name: my-frontend
    networks:
      - my-network
    environment:
      - VUE_APP_API_URL=jin-young.bae.takima.cloud/api

  httpd:
    build: ./http-server
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend
      - frontend

volumes:
  db-volume:

networks:
  my-network:
